# Generated by Django 6.0.6 on 2026-06-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome no WhatsApp')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frasco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_perfume', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_ml', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por ML (R$)')),
                ('link_fragrantica', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Disponível'), ('FECHADO', 'Fechado/Esgotado')], default='ABERTO', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pix (R$)')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, help_text='Ex: Abatimento de dívida antiga da planilha', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_ml', models.IntegerField(verbose_name='Quantidade (ML)')),
                ('tipo_pedido', models.CharField(choices=[('SPLIT', 'Split Normal'), ('APC', 'Apresentação Completa')], default='SPLIT', max_length=20)),
                ('pago', models.BooleanField(default=False, verbose_name='Pagamento Realizado?')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacao.cliente')),
                ('frasco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacao.frasco')),
            ],
        ),
    ]
