# Generated by Django 6.0.6 on 2026-08-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frasco',
            name='ml_disponiveis',
            field=models.IntegerField(blank=True, null=True, verbose_name='ML disponíveis'),
        ),
        migrations.AddField(
            model_name='frasco',
            name='ml_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume total (ML)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_ml', models.IntegerField(verbose_name='ML transferidos')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('frasco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacao.frasco')),
                ('pedido_cedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_cedidas', to='operacao.pedido')),
                ('pedido_destinatario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_origem', to='operacao.pedido')),
            ],
        ),
    ]
